### ISSUE TITLE
FB login blocked. App not set up: THis app is still in development mode, and you don't have access to it. Switch to a registered test user or ask an app admin for permission.

### ISSUE THREAD

**Issue by Dhua-v** [singhbhavneet/chat_app#10]
This is the blocking message from fb logging,  I am getting when trying to login.

**Comment by Dhua-v** [comment]
@singhbhavneet If possibel can you add me as a user pls.

**Comment by ghost** [comment]
@Dhua-v  At first you need to setup the application in **("https://developers.facebook.com")**. There would around 10 steps to enable Facebook login. After completing the process you need to make the app from **In Development** to **Live**, For that you need to provide Privacy Policy URL & Terms and Privacy terms.

@Dhua-v After Completing all these process you won't get that issue ("https://github.com/singhbhavneet/chat_app/issues/10").
