### ISSUE TITLE
lots of errors and warnings when building

### ISSUE THREAD

**Issue by sgehrman** [singhbhavneet/chat_app#4]
code is also not formatted correctly.

 ![image](https://user-images.githubusercontent.com/287137/71515250-2e2a2080-2857-11ea-980f-d9bef05f82ba.png)

**Comment by sgehrman** [comment]
Gradle does not have execution permission.
    You should change the ownership of the project directory to your user, or move the project to a directory with execute permissions.
Gradle task assembleDebug failed with exit code 1

**Comment by singhbhavneet** [comment]
@sgehrman  You can create pull request for this and I will accept that immediately

**Comment by Hiyorimi** [comment]
Gradle ownership problem can be resolved with `chmod a+rx android/gradlew`

**Comment by samatzhusup** [comment]
> Gradle ownership problem can be resolved with `chmod a+rx android/gradlew`

как вы решили это проблеmу?

**Comment by Hiyorimi** [comment]
> > Gradle ownership problem can be resolved with `chmod a+rx android/gradlew`
> 
> как вы решили это проблеmу?

you can type that in terminal in the directory of your project

**Comment by samatzhusup** [comment]
извините у меня еще вопрос: у меня проблема с регистрация через фейсбук не работает как можно это исправить ?

**Comment by samatzhusup** [comment]
> you can type that in terminal in the directory of your project

извините у меня еще вопрос: у меня проблема с регистрация через фейсбук не работает как можно это исправить ?

**Comment by singhbhavneet** [comment]
Fixed
