### ISSUE TITLE
camera_screen error

### ISSUE THREAD

**Issue by samatzhusup** [singhbhavneet/chat_app#6]
i have this error 

![2020-04-07_14-39-17](https://user-images.githubusercontent.com/50781959/78648596-fe6ec800-78dd-11ea-90f3-fcc8770deede.png)

**Comment by jtkeyva** [comment]
Getting same error for PermissionGroup. Any ideas?

**Comment by samatzhusup** [comment]
> Getting same error for PermissionGroup. Any ideas?

i removed this getPermissions()

**Comment by jtkeyva** [comment]
@samatzhusup thanks. That went away but I'm getting tons of errors trying to build. Can you please describe what steps you took to get this to build? What version of Dart/Flutter/Cocoapods/Xcode etc are you using? I've been smashing my head against the keyboard trying to get this to build... any help & explanation greatly appreciated!

Here's some errors:

> [!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_sysopen+-+%2FUsers%2Fme%2Fdev%2Fflutter%2Fchat_app%2Fios%2FPods%2FLocal+Podspecs%2Fonesignal.podspec.json&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

> /Users/me/dev/flutter/chat_app/ios/Flutter/Debug.xcconfig:1: could not find included file 'Pods/Target Support Files/Pods-Runner/Pods-Runner.debug.xcconfig' in search paths

> 'OneSignal/OneSignal.h'` file not found

**Comment by singhbhavneet** [comment]
Fixed
